### ISSUE TITLE
Could not connect to peers.

### ISSUE THREAD

**Issue by blackdragonth** [tineola/tineola#2]
I my environment, I am quite sure that I use the right MSP ID and connect to the right peer. But I keep getting this error:
============ Begin Error Snippet =============
tineola$ peer-set grpcs://[my peer IP]:7051
Connecting to peer grpcs://[my peer IP]:7051
Retrieving server keys from peer and CA server. If this fails please pass a chain file with the --pem option.
E1024 11:58:54.656172751    5610 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/home/sunt/tineola/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
    at /home/sunt/tineola/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15
error: [Client.js]: Failed Channels Query. Error: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/home/sunt/tineola/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
    at /home/sunt/tineola/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15
Error: 14 UNAVAILABLE: Connect Failed

tineola$ E1024 11:58:55.452159156    5610 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E1024 11:58:56.837892155    5610 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E1024 11:58:59.301513561    5610 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E1024 11:59:03.049376308    5610 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E1024 11:59:08.998714567    5610 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
tineola$ 
tineola$ E1024 11:59:17.683933198    5610 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
========== End Of Error Snippet =============

On the peer site, I was getting these errors in the log.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/22418655/67455241-4911c600-f657-11e9-8c31-0c4c96b0c0bf.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/22418655/67455310-75c5dd80-f657-11e9-9024-2e93ab91ed02.png">

Please clarify.

Thank you in advance

**Comment by parsiya** [comment]
What application are you running? Are you running the example from the wiki?

**Comment by starkriedesel** [comment]
Yes, I had discovered this when testing last week. I discovered that only NodeJS 8.x will work as other versions are either incompatible with dependencies or cause issues with the grpc native module. I have also committed some bug fixes today including updating some dependencies so please pull the latest and try again with NodeJS 8.x (I use NVM (https://github.com/nvm-sh/nvm) on my mac). Let me know if that works for you.

The other option is to use the proxy.js file which I created to strip ssl off of the connection (since GRPC doesn't permit skipping certificate validation). You can call it like ` ./proxy.js localhost:5071 1234` to start open a local port (localhost only) on tcp 1234 which proxies all traffic to a ssl port localhost:5071. Then in Tineola just point peer-set to your new local proxy port.

**Comment by blackdragonth** [comment]
Solved.

Thank you.
